/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/alerts/unsubscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Unsubscribe
         * @description One click, no login — the link has to work from an email client.
         *
         *     The token is signed and names a single saved search, so it can only ever
         *     switch off the one it was minted for.
         */
        get: operations["unsubscribe_api_alerts_unsubscribe_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auth Config
         * @description Lets the UI hide the sign-in button when the server can't honour it.
         */
        get: operations["auth_config_api_auth_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google Callback */
        get: operations["google_callback_api_auth_google_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google Start */
        get: operations["google_start_api_auth_google_start_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        /**
         * Delete Account
         * @description Remove the account and everything hanging off it.
         *
         *     Feature tables declare ON DELETE CASCADE against users.id, so this is one
         *     statement rather than a list that drifts as features are added.
         */
        delete: operations["delete_account_api_auth_me_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export My Data
         * @description Everything this account holds, as JSON. GDPR Art. 20 (portability).
         *
         *     Deliberately the raw rows rather than a rendered view: the point is that
         *     the data leaves in a form another tool can read, not that it looks nice.
         *
         *     Note what is *not* here — the people on the map. Their entries are not this
         *     user's personal data, and a saved list is exported as the opaque
         *     `person_key` plus whatever note the user wrote themselves. Exporting other
         *     people's profiles because someone bookmarked them would turn a portability
         *     request into a data dump about third parties.
         */
        get: operations["export_my_data_api_me_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List People
         * @description State only — the profiles themselves come from /api/profiles.
         */
        get: operations["list_people_api_me_people_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/people/{person_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Person State
         * @description Partial upsert: fields left unset keep their current value.
         */
        put: operations["set_person_state_api_me_people__person_key__put"];
        post?: never;
        /** Clear Person State */
        delete: operations["clear_person_state_api_me_people__person_key__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Profile */
        get: operations["get_my_profile_api_me_profile_get"];
        /** Put My Profile */
        put: operations["put_my_profile_api_me_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/searches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Searches */
        get: operations["list_searches_api_me_searches_get"];
        put?: never;
        /** Create Search */
        post: operations["create_search_api_me_searches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/searches/{search_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Search */
        delete: operations["delete_search_api_me_searches__search_id__delete"];
        options?: never;
        head?: never;
        /** Update Search */
        patch: operations["update_search_api_me_searches__search_id__patch"];
        trace?: never;
    };
    "/api/meta/interests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Interest Counts
         * @description Global counts, so the filter chips don't renumber as you filter.
         */
        get: operations["interest_counts_api_meta_interests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Source Counts
         * @description Subreddits actually present in the data, biggest first.
         *
         *     Read from the posts rather than from config, so a source that was ingested
         *     once and later removed from the env still labels its own rows.
         */
        get: operations["source_counts_api_meta_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta/writing-tips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Writing Tips
         * @description Measured gaps in the real corpus, for the post composer.
         *
         *     Every number here is computed from the live board. The app cannot say
         *     which posts *got replies* — Reddit's Atom feed carries no comment count
         *     and nothing stores one — so this deliberately reports what is missing
         *     rather than what "works". Advice the data cannot support isn't given.
         */
        get: operations["writing_tips_api_meta_writing_tips_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Profiles */
        get: operations["list_profiles_api_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{post_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_profiles__post_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats */
        get: operations["stats_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Newest Post At */
            newest_post_at: string | null;
            /** Posts */
            posts: number;
            /** Profiles */
            profiles: number;
            /** Status */
            status: string;
        };
        /** InterestCount */
        InterestCount: {
            /** Count */
            count: number;
            /** Slug */
            slug: string;
        };
        /** LabelCount */
        LabelCount: {
            /** Count */
            count: number;
            /** Label */
            label: string;
        };
        /** PersonOut */
        PersonOut: {
            /** Age */
            age: number | null;
            /** Body */
            body: string;
            /** City */
            city: string | null;
            /** Days Ago */
            days_ago: number;
            /** Gender */
            gender: string;
            /** Id */
            id: string;
            /** Interests */
            interests: string[];
            /** Lang */
            lang: string;
            /** Lat */
            lat: number | null;
            /** Lon */
            lon: number | null;
            /** Looking For */
            looking_for: string | null;
            /**
             * Match Reasons
             * @default []
             */
            match_reasons: string[];
            /** Match Score */
            match_score?: number | null;
            /** Needs Review */
            needs_review: boolean;
            /** Permalink */
            permalink: string;
            /**
             * Person Key
             * @default
             */
            person_key: string;
            /**
             * Posted At
             * Format: date-time
             */
            posted_at: string;
            /** Precision */
            precision: string;
            /** Province */
            province: string | null;
            /** Repeat Count */
            repeat_count: number;
            /** Subreddit */
            subreddit: string;
            /** Summary */
            summary: string;
            /** Title */
            title: string;
            /** X */
            x: number | null;
            /** Y */
            y: number | null;
        };
        /**
         * PersonStateIn
         * @description Partial update. Unset fields keep their stored value.
         */
        PersonStateIn: {
            /** Note */
            note?: string | null;
            /** Saved */
            saved?: boolean | null;
            /**
             * Set Status
             * @default false
             */
            set_status: boolean;
            /** Status */
            status?: string | null;
        };
        /** PersonStateOut */
        PersonStateOut: {
            /** Note */
            note: string;
            /** Person Key */
            person_key: string;
            /** Saved */
            saved: boolean;
            /** Status */
            status: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProfileListOut */
        ProfileListOut: {
            /** People */
            people: components["schemas"]["PersonOut"][];
            /** Placed */
            placed: number;
            /** Total */
            total: number;
            /** Unplaced */
            unplaced: number;
        };
        /** SavedSearchIn */
        SavedSearchIn: {
            /**
             * Cadence
             * @default weekly
             */
            cadence: string;
            /** Filters */
            filters: Record<string, never>;
            /** Name */
            name: string;
        };
        /**
         * SavedSearchOut
         * @description A saved search as the account page shows it.
         *
         *     There was a `new_matches: int = 0` here. Nothing ever assigned it and the
         *     frontend never read it, so the API advertised a count that was always zero —
         *     the schema promising a capability that did not exist. Removed rather than
         *     implemented: "new since you last looked" needs a decision about what the
         *     user has *seen*, which is not the same as what the last digest announced,
         *     and `alerts_sent` only records the latter.
         */
        SavedSearchOut: {
            /** Cadence */
            cadence: string;
            /** Filters */
            filters: Record<string, never>;
            /** Id */
            id: number;
            /** Last Match At */
            last_match_at: string | null;
            /** Last Run At */
            last_run_at: string | null;
            /** Name */
            name: string;
        };
        /** SavedSearchPatch */
        SavedSearchPatch: {
            /** Cadence */
            cadence?: string | null;
            /** Name */
            name?: string | null;
        };
        /** StatsOut */
        StatsOut: {
            /** Active 30D */
            active_30d: number;
            /** Age Buckets */
            age_buckets: components["schemas"]["LabelCount"][];
            /** Cities Covered */
            cities_covered: number;
            /** Interest Counts */
            interest_counts: components["schemas"]["LabelCount"][];
            /** Median Age */
            median_age: number | null;
            /** New This Week */
            new_this_week: number;
            /** Newest Post At */
            newest_post_at: string | null;
            /** Posts Per Week */
            posts_per_week: number[];
            /** Top Cities */
            top_cities: components["schemas"]["LabelCount"][];
        };
        /**
         * UserOut
         * @description What the browser is told about the signed-in account. Nothing more.
         */
        UserOut: {
            /** Email */
            email: string;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Picture */
            picture: string;
        };
        /** UserProfileIn */
        UserProfileIn: {
            /** Age */
            age?: number | null;
            /** Age Max */
            age_max?: number | null;
            /** Age Min */
            age_min?: number | null;
            /** City */
            city?: string | null;
            /**
             * Interests
             * @default []
             */
            interests: string[];
            /** Province */
            province?: string | null;
        };
        /**
         * UserProfileOut
         * @description The viewer's own self-description, used only for match ranking.
         */
        UserProfileOut: {
            /** Age */
            age: number | null;
            /** Age Max */
            age_max: number | null;
            /** Age Min */
            age_min: number | null;
            /** City */
            city: string | null;
            /** Interests */
            interests: string[];
            /** Province */
            province: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WritingTipsOut
         * @description Measured gaps in the corpus, for the post composer.
         *
         *     Note what is absent: any claim about which posts got replies. The feed
         *     carries no comment count, so that would be invention.
         */
        WritingTipsOut: {
            /** Gaps */
            gaps: components["schemas"]["LabelCount"][];
            /** Median Length */
            median_length: number;
            /** Sample Size */
            sample_size: number;
            /** Top Interests */
            top_interests: components["schemas"]["LabelCount"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    unsubscribe_api_alerts_unsubscribe_get: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_config_api_auth_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    google_callback_api_auth_google_callback_get: {
        parameters: {
            query?: {
                code?: string | null;
                state?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_start_api_auth_google_start_get: {
        parameters: {
            query?: {
                next?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"] | null;
                };
            };
        };
    };
    delete_account_api_auth_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    export_my_data_api_me_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    list_people_api_me_people_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonStateOut"][];
                };
            };
        };
    };
    set_person_state_api_me_people__person_key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonStateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonStateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_person_state_api_me_people__person_key__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_profile_api_me_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileOut"];
                };
            };
        };
    };
    put_my_profile_api_me_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_searches_api_me_searches_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedSearchOut"][];
                };
            };
        };
    };
    create_search_api_me_searches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedSearchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedSearchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_search_api_me_searches__search_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                search_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_search_api_me_searches__search_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                search_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedSearchPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedSearchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    interest_counts_api_meta_interests_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterestCount"][];
                };
            };
        };
    };
    source_counts_api_meta_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabelCount"][];
                };
            };
        };
    };
    writing_tips_api_meta_writing_tips_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WritingTipsOut"];
                };
            };
        };
    };
    list_profiles_api_profiles_get: {
        parameters: {
            query?: {
                /** @description Days back; omit or 0 for all time */
                period?: number | null;
                age_min?: number;
                age_max?: number;
                /** @description Comma list: M,F,NB,couple,unknown */
                genders?: string | null;
                /** @description Comma list of interest slugs */
                interests?: string | null;
                interest_mode?: string;
                /** @description Comma list: nl,en */
                langs?: string | null;
                /** @description Comma list of province names */
                provinces?: string | null;
                /** @description Comma list of subreddits, no 'r/' */
                sources?: string | null;
                search?: string | null;
                /** @description saved | contacted | hidden | none. Signed in only. */
                state?: string | null;
                sort?: string;
                include_hidden?: boolean;
                include_events?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_profiles__post_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats_api_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOut"];
                };
            };
        };
    };
}
